export const locations = [{town: 'Abingdon', coords: [-1.2878968802672597, 51.67178136767836]}, {town: 'Henley', coords: [-0.9033067471332705, 51.53710356800439]}, {town: 'Oxford', coords: [-1.2577162566127518, 51.754024253642946]}, {town: 'Wantage', coords: [-1.426433149561529, 51.59018592067826]}, {town: 'Witney', coords: [-1.4848687355795065, 51.78721320217527]}, {town: 'Woodstock', coords: [-1.354313034285376, 51.84827550604427]}, {town: 'County Durham', coords: [-1.5796296224151827, 54.776266361541865]}, {town: 'Newcastle Upon Tyne', coords: [-1.6177062075052513, 54.98107999137656]}, {town: 'Northumberland', coords: [-1.7710249970488148, 55.344617191042744]}];
export const health = [{title:'Memory and Mood', name: 'memory'}, {title: 'Medication', name: 'medication'}, {title: 'Mobility', name: 'mobility'}, {title: 'Hearing', name: 'hearing'}, {title: 'Vision', name: 'vision'}];
export const leisure = [{title: 'Gardening and outdoors', name: 'gardening'}, {title: 'Arts and Crafts', name: 'arts'}, {title: 'Puzzles and Quizes', name: 'puzzles'}, {title: 'Exercise and fitness', name: 'exercise'}, {title: 'Hobbies and leisure', name: 'hobbies'}, {title: 'Listening to music, radio, or audio books', name: 'listening'}];
export const home = [{title: 'House hold chores and hygiene', name: 'chores'}, {title: 'DIY and maintenance', name: 'DIY'}, {title: 'Stairs', name: 'stairs'}, {title: 'Cooking and meals', name: 'cooking'}];
export const security = [{title: 'Help in emergencies', name: 'emergencies'}, {title: 'Living alone', name: 'alone'}, {title: 'Living alone', name: 'alone'}, {title: 'In the kitchen', name: 'kitchen'}, {title: 'In the bathroom', name: 'bathroom'}];

export const support = [{title: 'Yes', name: 'yes'}, {title: 'No', name: 'no'}];
export const week = [{title: 'Monday', name: 'monday'}, {title: 'Tuesday', name: 'tuesday'}, {title: 'Wednesday', name: 'wednesday'}, {title: 'Thursday', name: 'thursday'}, {title: 'Friday', name: 'friday'}, {title: 'Saturday', name: 'saturday'}, {title: 'Sunday', name: 'sunday'}];

let reviews = [{review: 'My penguin loves to play with it.', author: 'Sophie Davis', town: 'Abingdon'}, {review: 'I saw one of these in Algeria and I bought one.', author: 'Daniel Johnson', town: 'Oxford'},  {review: 'This Speaking Day Clock is hyper.', author: 'Charlotte Rodriguez', town: 'Witney'},  {review: 'My neighbor Betha has one of these. She works as a teacher and she says it looks wide.', author: 'Joseph Davis', town: 'Wantage'}, {review: 'My chicken loves to play with it.', author: 'Chloe Johnson', town: 'Abingdon'}, {review: 'This Speaking Day Clock works excessively well. It mortally improves my golf by a lot.', author: 'William Wilson', town: 'Henley'},  {review: 'My neighbor Allean has one of these. She works as a sky diver and she says it looks weedy.', author: 'Megan Jones', town: 'County Durham'}, {review: 'I use it once a week when I\'m in my firetruck.', author: 'Jim Lahey', town: 'Northumberland'}]
export const products = [
    {title: 'Speaking Day Clock', description: 'Pastry sweet carrot cake fruitcake cheesecake jelly-o gummi bears liquorice. Wafer sugar plum sweet sesame snaps cake soufflé. Powder bear claw pie jelly-o danish jelly beans sesame snaps soufflé liquorice.', price: '19.99', rating: 5, reviews: reviews, image: 'http://placekitten.com/300/300'}, 
    {title: 'Bathroom aids', description: 'Pastry sweet carrot cake fruitcake cheesecake jelly-o gummi bears liquorice. Wafer sugar plum sweet sesame snaps cake soufflé. Powder bear claw pie jelly-o danish jelly beans sesame snaps soufflé liquorice.', price: '29.99', rating: 5, reviews: reviews, image: 'http://placekitten.com/300/300'}, 
    {title: 'Mini Juke Box', description: 'Pastry sweet carrot cake fruitcake cheesecake jelly-o gummi bears liquorice. Wafer sugar plum sweet sesame snaps cake soufflé. Powder bear claw pie jelly-o danish jelly beans sesame snaps soufflé liquorice.', price: '12.99', rating: 3, reviews: reviews, image: 'http://placekitten.com/300/300'}, 
    {title: 'Colouring books', description: 'Pastry sweet carrot cake fruitcake cheesecake jelly-o gummi bears liquorice. Wafer sugar plum sweet sesame snaps cake soufflé. Powder bear claw pie jelly-o danish jelly beans sesame snaps soufflé liquorice.', price: '6.99', rating: 4, reviews: reviews, image: 'http://placekitten.com/300/300'}];
export const services = [{}];

export const initValues = [{title: 'Health and Wellbeing', name: 'health'}, {title: 'Leisure and Play', name: 'leisure'}, {title: 'Living at Home', name: 'home'}, {title: 'Security', name: 'security'}];
